# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RoR-Angular-Back_development
  username: arturo
  password: postgresql123
  host: localhost

test:
  <<: *default
  database: RoR-Angular-Back_test


production:
  <<: *default
  database: RoR-Angular-Back_production
  username: RoR-Angular-Back
  password: <%= ENV['ROR-ANGULAR-BACK_DATABASE_PASSWORD'] %>
